when:
  - event: pull_request
    branch: main
  - event: push
    branch: main
  - event: release

matrix:
  # Override Node.js version over mise.toml
  MISE_NODE_VERSION:
    - 20
    - 22
    - 24

steps:
  - name: test
    commands:
      - mise install
      - mise test
